name: Create tag on develop

on:
  push:
    branches: [ main ]

jobs:
  release_on_push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  steps:
    - uses: rymndhng/release-on-push-action@v0.20.0
      with:
        bump_version_scheme: minor
