# This is a basic workflow that is manually triggered.
# It would be used execute onetimer/manual tasks.
name: Staging - Custom tasks

on:
  workflow_dispatch:
    inputs:
      task_name:
        description: 'Provide name of the task (eg: custom_task:create_sample_articles)'
        required: true

jobs:
  execute_task:
    name: Custom task execution
    runs-on: ubuntu-latest
    concurrency: staging_environment
    environment: staging
    env:
      STAGING_SERVER_IP_ONE: ${{ secrets.SG_STAGING_SERVER_IP_ONE }}
      SG_RAILS_MASTER_KEY: ${{ secrets.SG_RAILS_MASTER_KEY }}

    steps:
      - name: Install Github actions key to runner
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}
          name: github-actions
          known_hosts: unnecessary

      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Executing custom task on staging
        working_directory:
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          export RAILS_ENV="staging" && SECRET_KEY_BASE=dummy RAILS_ENV=staging bundle exec rake ${{ github.event.inputs.task_name }} --trace
