name: Authenticator workflow

on:
  workflow_call:
    inputs:
      secret_key:
        required: true
        type: string
    secrets:
      staging_secret_key:
        required: true

jobs:
  secrets-gate:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      secret_key_valid: ${{ steps.check_secrets.outputs.secret_key_valid }}
    steps:
      - name: Check for secrets needed to run workflow
        id: check_secrets
        run: echo '::set-output name=secret_key_valid::${{ secrets.staging_secret_key == inputs.secret_key }}'

      - name: Fail job if secret is not valid
        if: ${{ steps.check_secrets.outputs.secret_key_valid != 'true' }}
        run: exit 1