name: Deploy to staging server

on:
  # Manually deploy branch
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    name: Capistrano Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
          config: |
            host 34.219.95.227
              IdentityFile ~/.ssh/github-actions
              IdentitiesOnly yes
              ForwardAgent yes

      - name: Adding Known Hosts
        run: ssh-keyscan -H 34.219.95.227 -v

      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Deploy to staging
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          bundle exec cap staging deploy
