name: Deploy To Staging Server Two

on:
  # Manually deploy branch
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    name: Capistrano Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: miloserdow/capistrano-deploy@master
        with:
          target: development # Defines the environment that will be used for the deployment
          #deploy_key: ${{ secrets.SSH_KEY }} # Name of the variable configured in Settings/Secrets of your github project
          enc_rsa_key_val: ${{ secrets.SSH_KEY }}
          working-directory: /home/ubuntu/workspace/my_app
