name: Staging - Deploy To staging

on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
#      xxt_all:
#        description: 'xxt-all'
#        required: false
#        type: boolean
      sgt_core:
        description: 'sgt-core'
        required: false
        type: boolean
      myt_core:
        description: 'myt-core'
        required: false
        type: boolean
      hkt_core:
        description: 'hkt-core'
        required: false
        type: boolean
#      xxtup_all:
#        description: 'xxtup-all'
#        required: false
#        type: boolean
      sgtup_core:
        description: 'sgtup-core'
        required: false
        type: boolean
      mytup_core:
        description: 'mytup-core'
        required: false
        type: boolean
      hktup_core:
        description: 'hktup-core'
        required: false
        type: boolean
      sandbox2_core:
        description: 'sandbox2.cardup.co'
        required: false
        type: boolean
      sgscan_core:
        description: "sgscan-core __________________________[Note: this workflow would do the deployment only. After that, you need to execute 'db:seed','restart' as a Custom tasks]"
        required: false
        type: boolean
#      seed:
#        description: 'Execute Seed?'
#        required: false
#        type: boolean

jobs:
  deploy:
    name: Capistrano Deploy to Staging Server
    runs-on: ubuntu-latest
    concurrency: staging_environment
    environment: staging
    env:
      # Servers
      STAGING_SERVER_IP_ONE: ${{ secrets.SG_STAGING_SERVER_IP_ONE }}
      STAGING_SERVER_IP_TWO: ${{ secrets.SG_STAGING_SERVER_IP_TWO }}
      # User inputs
      #XXT_ALL: ${{ github.event.inputs.xxt_all }}
      SGT: ${{ github.event.inputs.sgt_core }}
      MYT: ${{ github.event.inputs.myt_core }}
      HKT: ${{ github.event.inputs.hkt_core }}
      #XXTUP_ALL: ${{ github.event.inputs.xxtup_all }}
      SGTUP: ${{ github.event.inputs.sgtup_core }}
      MYTUP: ${{ github.event.inputs.mytup_core }}
      HKTUP: ${{ github.event.inputs.hktup_core }}
      SANDBOX2: ${{ github.event.inputs.sandbox2_core }}
      SGSCAN: ${{ github.event.inputs.sgscan_core }}

    steps:
      - name: Install Github actions key to runner
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}
          name: github-actions
          known_hosts: unnecessary

      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Deploy to staging
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          bundle exec cap staging deploy

#      - name: DB migration
#        if: ${{ success() }}
#        run: |
#          eval "$(ssh-agent -s)"
#          ssh-add ~/.ssh/github-actions
#          bundle exec cap staging deploy:migrate
#
#      - name: DB seed
#        if: ${{ github.event.inputs.seed == 'true' }}
#        run: |
#          eval "$(ssh-agent -s)"
#          ssh-add ~/.ssh/github-actions
#          bundle exec cap staging deploy:seed
#
#      - name: Restart server
#        if: ${{ success() }}
#        run: |
#          eval "$(ssh-agent -s)"
#          ssh-add ~/.ssh/github-actions
#          bundle exec cap staging deploy:restart
