name: Test Deploy To Staging Server

on:
  # Manually deploy branch
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    name: Test Capistrano Deploy to Staging Server
    runs-on: ubuntu-latest
    environment: staging
    env:
      STAGING_SERVER_IP: ${{ secrets.SSH_HOST }}

    steps:
      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'

      - name: Install SSH key to Server for deploy_user
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_ID_RSA }}
          name: id_rsa
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'

      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Deploy to staging
        working-directory:
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          ssh-add ~/.ssh/id_rsa
          bundle exec cap staging deploy
