name: Staging - Deploy To staging

on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
#      xxt_all:
#        description: 'xxt-all'
#        required: false
#        type: boolean
      xxt_sg:
        description: 'xxt-sg'
        required: false
        type: boolean
      xxt_my:
        description: 'xxt-my'
        required: false
        type: boolean
      xxt_hk:
        description: 'xxt-hk'
        required: false
        type: boolean
#      xxtup_all:
#        description: 'xxtup-all'
#        required: false
#        type: boolean
      xxtup_sg:
        description: 'xxtup-sg'
        required: false
        type: boolean
      xxtup_my:
        description: 'xxtup-my'
        required: false
        type: boolean
      xxtup_hk:
        description: 'xxtup-hk'
        required: false
        type: boolean
      sandbox2:
        description: 'sandbox2'
        required: false
        type: boolean
      sgscan:
        description: 'sgscan'
        required: false
        type: boolean
#      seed:
#        description: 'Execute Seed?'
#        required: false
#        type: boolean

jobs:
  deploy:
    name: Capistrano Deploy to Staging Server
    runs-on: ubuntu-latest
    concurrency: staging_environment
    environment: staging
    env:
      # Servers
      STAGING_SERVER_IP_ONE: ${{ secrets.SG_STAGING_SERVER_IP_ONE }}
      STAGING_SERVER_IP_TWO: ${{ secrets.SG_STAGING_SERVER_IP_TWO }}
      # User inputs
      XXT_ALL: ${{ github.event.inputs.xxt_all }}
      XXT_SG: ${{ github.event.inputs.xxt_sg }}
      XXT_MY: ${{ github.event.inputs.xxt_my }}
      XXT_HK: ${{ github.event.inputs.xxt_hk }}
      XXTUP_ALL: ${{ github.event.inputs.xxtup_all }}
      XXTUP_SG: ${{ github.event.inputs.xxtup_sg }}
      XXTUP_MY: ${{ github.event.inputs.xxtup_my }}
      XXTUP_HK: ${{ github.event.inputs.xxtup_hk }}
      SANDBOX2: ${{ github.event.inputs.sandbox2 }}
      #SGSCAN: ${{ github.event.inputs.sgscan }}

    steps:
      - name: Install Github actions key to runner
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_GITHUB_ACTIONS }}
          name: github-actions
          known_hosts: unnecessary

      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Deploy to staging
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          bundle exec cap staging deploy

#      - name: DB migration
#        if: ${{ success() }}
#        run: |
#          eval "$(ssh-agent -s)"
#          ssh-add ~/.ssh/github-actions
#          bundle exec cap staging deploy:migrate
#
#      - name: DB seed
#        if: ${{ github.event.inputs.seed == 'true' }}
#        run: |
#          eval "$(ssh-agent -s)"
#          ssh-add ~/.ssh/github-actions
#          bundle exec cap staging deploy:seed
#
#      - name: Restart server
#        if: ${{ success() }}
#        run: |
#          eval "$(ssh-agent -s)"
#          ssh-add ~/.ssh/github-actions
#          bundle exec cap staging deploy:restart
