name: Test Deploy To Staging Server

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    name: Test Capistrano Deploy to Staging Server
    runs-on: ubuntu-latest
    concurrency: staging_environment
    environment: staging
    env:
      STAGING_SERVER_IP: ${{ secrets.SG_SGT_STAGING_SERVER_IP }}

    steps:
      - name: Install Github actions key to runner
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: github-actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'

      - name: Install target server - deploy user key to runner
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_ID_RSA }}
          name: id_rsa
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'

      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Deploy to staging
        working-directory:
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          ssh-add ~/.ssh/id_rsa
          bundle exec cap staging deploy

      - name: DB migration
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          ssh-add ~/.ssh/id_rsa
          bundle exec cap staging deploy:migrate

      - name: Restart server
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github-actions
          ssh-add ~/.ssh/id_rsa
          bundle exec cap staging deploy:restart
